### PR TITLE
Annotation feature

### PR DESCRIPTION
**Pull request by fr43nk**
show the annotation information of the current file in the same window.

### CODE REVIEW

**Comment by OpenNingia** [comment]
Could you please rebase your feature branch to avoid resolving conflicts in the master one?

**Comment by fr43nk** [comment]
It was a big mess to merge the latest master into my dev branch. I hope everything still works.

**Comment by fr43nk** [comment]
Sorry for all the confusion. I cleaned my yesterdays merge. Now it should be all fine. Although there seem to be a lot of changes in the package.json, it is not. I just added the new configuration setting. The rest is as in master:latest.

**Comment by fr43nk** [comment]
This feature relates to #12

**Pull request merged**
